version: '{build}'
clone_depth: 1

platform: x64

clone_folder: c:\gopath\src\github.com\fibercrypto\fibercryptowallet

environment:
  GOPATH: c:\gopath
  GOROOT: C:\go
  QT5_BASE_DIR: C:/Qt/5.13.0/msvc2017
  QT_DIR: C:/Qt
  QT_QMAKE_DIR: C:/Qt/5.13.0/mingw73_64/bin

install:
  - set PATH=%GOPATH%\bin;%GOROOT%\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - bash -c "ls C:/Qt"
  - choco install make -y
  - make install-deps-Windows
  - make install-linters
  - make install-coveralls

test_script:
  - make build-Windows-travis
  - make test
  - make lint
  - make test-cover-travis

build: off
deploy: off
