sudo: required
language: go
go:
- 1.11.1

services:
- docker

go_import_path: github.com/fibercrypto/FiberCryptoWallet

matrix:
  include:
  - stage: "RPI"
    if: branch = release*$
    install:
    - docker pull therecipe/qt:rpi1
    - docker pull therecipe/qt:rpi2
    - docker pull therecipe/qt:rpi3
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    
    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build rpi1
    - $GOPATH/bin/qtdeploy -docker build rpi2
    - $GOPATH/bin/qtdeploy -docker build rpi3

  - stage: "Android"
    if: branch = release*$

    install:
    - docker pull therecipe/qt:android
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...

    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build android
    - $GOPATH/bin/qtdeploy -docker build android-emulator
    - make test

  - stage: "Linux"
    install:
    - docker pull therecipe/qt:linux
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    - make test
    
    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build desktop
    - make test
  
  - stage: "Windows"
    os: windows
    install:
    - go get -u -v github.com/therecipe/qt/cmd/...
    - ($(go env GOPATH)\bin\qtsetup -test=false | true)
    
    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy build desktop 
    - make test

  - stage: "MacOS"
    os: osx
    osx_image: xcode10.2
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - xcode-select --install | true
    - go get -u -v github.com/therecipe/qt/cmd/... && ($(go env GOPATH)/bin/qtsetup -test=false | true)
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy build desktop
    - make test
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
