sudo: required
language: go
go:
  - 1.11.1

services:
  - docker

go_import_path: github.com/fibercrypto/FiberCryptoWallet

env:
  global:
  - XARGS="-screen 0 1024x768x24"

matrix:
  include:
    - stage: "RPI"
      if: branch = release*$
      install:
        - DEFAULT_ARCH=rpi1 make install-docker-deps
        - DEFAULT_ARCH=rpi2 make install-docker-deps
        - DEFAULT_ARCH=rpi3 make install-docker-deps
        - make install-deps-no-envs

      script:
        - make clean
        - DEFAULT_TARGET=rpi1 make build-docker
        - DEFAULT_TARGET=rpi2 make build-docker
        - DEFAULT_TARGET=rpi3 make build-docker
        - make lint
        - make test

    - stage: "Android"
      if: branch = release*$

      install:
        - DEFAULT_ARCH=android make install-docker-deps
        - make install-deps-no-envs

      script:
        - make clean
        - DEFAULT_TARGET=android make build-docker
        - DEFAULT_TARGET=android-emulator make build-docker
        - make lint
        - make test

    - stage: "Linux"
    before_install:
    - source ./ci-scripts/install-$TRAVIS_OS_NAME.sh
      install:
        - make install-deps
        - make test

    before_script:
    # Install hardware wallet for running tests against emulator
    - mkdir -p tmp/hardware-wallet
    - git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git tmp/hardware-wallet
    - git -C tmp/hardware-wallet submodule update --init --recursive
    # Define env vars for Linux builds
    - export PATH="/usr/local/bin:$(pwd)/tmp/hardware-wallet/protoc/bin:$PATH"
    - echo "PATH=$PATH";
    - echo "PIP=$PIP";

      script:
        - make lint
        - make clean
        - make build
    - PYTHON=python3 PIP=pip3 make -C tmp/hardware-wallet clean
    - PYTHON=python3 PIP=pip3 make -C tmp/hardware-wallet/tiny-firmware/protob install-deps-nanopb
    - PYTHON=python3 PIP=pip3 make -C tmp/hardware-wallet/tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
    - PYTHON=python3 PIP=pip3 make -C tmp/hardware-wallet emulator
    # On GNU/Linux wrap emulator in xvfb graphics context
    - xvfb-run --server-args="${XARGS}" make -C ./tmp/hardware-wallet run-emulator & true;
    # Run self-tests
    - ps aux | grep emulator
        - make test

    - stage: "Windows"
      os: windows
      install:
        - choco install make -y
        - travis_wait make install-deps-Windows
        - make install-linters

      script:
        - make lint
        # - make build
        # - make test

    - stage: "MacOS"
      os: osx
      osx_image: xcode10.2
      install:
        - make install-deps

      script:
        - make lint
        - make clean
        - make build
        - make test
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
