sudo: required
language: go
go:
- 1.12.6
services:
- docker
go_import_path: github.com/fibercrypto/FiberCryptoWallet
env:
  global:
    secure: Kgk8K+M8Ean9KjB1Sbke9g3F/5LEDsOHRhuU3KMroOJbXOKVsfICj2Xu3DwBiuFmyBIDnV/DpDNjkZPSQYGDxIXyPDpOLqg549iyyH5Xrc3ecFXIWwk3ztU9HZsXGdy5YOj8LMDuqzq/6NZx5/sW6YMZtCzzXbBXeB6mLYeiaX1lrL4CB9rnDBgEG3gDkoHnI5eS9KTBhSgxIhVDn3/Tas5DWuAjDF+tkmKJGWG8CKN4raja6JsYlloCjzzzoS/EkW/hfEHahadpZIV6znej0KIVR3gQS3bQGp0Eim/9RnWGK273rapsksr16hZkQKCEIQcSahFG0r921Evwlt0kXoEtFIkaKynqt1pGGCD1YiwE/6hK6KB0zmp9rJkESl2z48g7CF87hoCJwTAk+FO853D7152qAAbMd46Fh4kDH5+KIfuuu8ew3WIkp4GNytYadu1yedGTHsESn9FEwJxxYSV0ZiGAbn5SXw8olZE7DbXK/aLghTaXOgBb/aBzbqIZIe4ZPDFm14v8BGU2mqPJdhFRi5QKDMHUBkZ1Uww95QwxTICzztVhlTZny01wiLaCPA1BNjvyWzbP4sHrOKNKCBgmPsBH1jAvINhAkeyNBn8lc8P8S8Va7iEJAGNgM8zarj6Nnt+iPbDi+48hHfcOMUoV+oGqh9t63+DDfCWQSp4=
matrix:
  include:
  - stage: RPI
    if: branch = release*$
    install:
    - DEFAULT_ARCH=rpi1 make install-docker-deps
    - DEFAULT_ARCH=rpi2 make install-docker-deps
    - DEFAULT_ARCH=rpi3 make install-docker-deps
    - make install-deps-no-envs
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - make clean
    - DEFAULT_TARGET=rpi1 make build-docker
    - DEFAULT_TARGET=rpi2 make build-docker
    - DEFAULT_TARGET=rpi3 make build-docker
    - make lint
    - make test
  - stage: Android
    if: branch = release*$
    install:
    - DEFAULT_ARCH=android make install-docker-deps
    - make install-deps-no-envs
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - make clean
    - DEFAULT_TARGET=android make build-docker
    - DEFAULT_TARGET=android-emulator make build-docker
    - make lint
    - make test
    - make test-cover-travis
  - stage: Linux
    install:
    - make install-docker-deps
    - make install-deps-no-envs
    - make install-linters
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - make clean
    - DEFAULT_TARGET=linux make build-docker
    - make test
    - make lint
    - make test-cover-travis
  - stage: Windows
    os: windows
    install:
    - choco install make -y
    - travis_wait make install-deps-Windows
    - make install-linters
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - make build
    - make test
    - make build-icon
    - make lint
    - make test-cover-travis
  - stage: MacOS
    os: osx
    osx_image: xcode10.2
    install:
    - make install-deps
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    script:
    - make clean
    - make build
    - make test
    - make build-icon
    - make lint
    - make test-cover-travis
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
before_deploy:
   - export VERSION="$(git describe --tags --exact-match HEAD 2> /dev/null)"
   - export ARCH="$(uname -m)"
   - export OS="$(uname -s)"
   - make prepare-release
   - make build
   - ( cd deploy && tar czf ../fibercryptowallet-${VERSION}-${OS}-${ARCH}.tar.gz ./*  )
   - pwd && ls -l .
deploy:
  provider: releases
  api_key:
    secure: DCM8aKdci6IA7dF9a84V6FEK+VkfEGoitre/wdxeZs7z4obKY41MhejHvWe017tuLhWqARwuud4PgEDcypVVDN2zB5d/D94O3JQHIDfL643WWTS7JOd+93vfOVmQ3jcGg5yRwt4T8fH3RUwNgQjagXeWLnoAhgAvUzGeAUN26AUFS4TXMmf0tnfGRGsrd8tMcnmsPxWcmrog1GllJ1m7GQ55ua1FuYV3ldyX6bnxQSx/B73T8pCvmz9OIW14nZVHgPrdOeVgHy2JlA10dKe59i1CTBevbo050CEIAque6RkzW52AQTKksmd/X2GnxODkqaZ8dux5b/uCv8Stht1jebM8AwZID8nmnmlpUHrafuZilu/m3RJ/j7YuF+UsNGOPeLG+z1tb3KcSENihRPsFOh4YHFTPHkDBbMcvg+2EKfbOIOrg/+js7Ycmmjx1NoLZgYpmMuq6mBu/TZDuFmFNVtDwevieG7berfVyvIyr3TJEdW+bm+vHGpdTcZho1cMrSmaB2r9j9UADKrRrRAU7vHCjozufg4+dnGjYHHQNCecpeirsbCymq3d7Wgezkm/LK4c0vDbtHuXo1q5VxrMjizzuBNCmiRyguGt0zSWvemU68x8W+OjmnFNJRyEa/g//2BLBQrn6A3qC+Qv5tn1REClW7xMcZXcDjIjmIW7z2Gw=
  file: fibercryptowallet-${VERSION}-${OS}-${ARCH}.tar.gz
  kip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: fibercrypto/FiberCryptoWallet
    tags: true

