sudo: required
language: go
go:
- 1.11.1

services:
- docker

matrix:
  include:
  - stage: "RPI"
    install:
    - docker pull therecipe/qt:rpi1
    - docker pull therecipe/qt:rpi2
    - docker pull therecipe/qt:rpi3
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build rpi1
    - $GOPATH/bin/qtdeploy -docker build rpi2
    - $GOPATH/bin/qtdeploy -docker build rpi3
  
  - stage: "Linux"
    install:
    - docker pull therecipe/qt:linux
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build linux
  
  - stage: "Windows"
    install:
    - docker pull therecipe/qt:windows_32_shared
    - docker pull therecipe/qt:windows_32_static
    - docker pull therecipe/qt:windows_64_shared
    - docker pull therecipe/qt:windows_64_static
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build windows_32_shared
    - $GOPATH/bin/qtdeploy -docker build windows_32_static
    - $GOPATH/bin/qtdeploy -docker build windows_64_shared
    - $GOPATH/bin/qtdeploy -docker build windows_64_static
  - os: osx
    osx_image: xcode10.2
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - xcode-select --install | true
    - go get -u -v github.com/therecipe/qt/cmd/... && ($(go env GOPATH)/bin/qtsetup -test=false | true)
    - go get -t -d -v ./...
    - make build-wallet 

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

