sudo: required
language: go
go:
- 1.11.1

services:
- docker

go_import_path: github.com/fibercrypto/FiberCryptoWallet

env:
  global:
  - XARGS="-screen 0 1024x768x24"

matrix:
  include:
  - stage: "RPI"
    if: branch = release*$
    install:
    - docker pull therecipe/qt:rpi1
    - docker pull therecipe/qt:rpi2
    - docker pull therecipe/qt:rpi3
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...
    
    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build rpi1
    - $GOPATH/bin/qtdeploy -docker build rpi2
    - $GOPATH/bin/qtdeploy -docker build rpi3

  - stage: "Android"
    if: branch = release*$

    install:
    - docker pull therecipe/qt:android
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...

    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build android
    - $GOPATH/bin/qtdeploy -docker build android-emulator

  - stage: "Linux"
    before_install:
    - source ./ci-scripts/install-$TRAVIS_OS_NAME.sh
    install:
    - docker pull therecipe/qt:linux
    - go get -v -tags=no_env github.com/therecipe/qt/cmd/...

    before_script:
    # Install hardware wallet for running tests against emulator
    - mkdir -p tmp/hardware-wallet
    - git clone --depth=1 --single-branch --branch develop https://github.com/skycoin/hardware-wallet.git tmp/hardware-wallet
    - git -C tmp/hardware-wallet submodule update --init --recursive
    # Define env vars for Linux builds
    - export PATH="/usr/local/bin:$(pwd)/tmp/hardware-wallet/protoc/bin:$PATH"
    - echo "PATH=$PATH";
    - echo "PIP=$PIP";

    script:
    - make -C tmp/hardware-wallet clean
    - PROTOC_VERSION=2.6.1 make -C tmp/hardware-wallet/tiny-firmware/protob install-protoc
    - make -C tmp/hardware-wallet/tiny-firmware/protob/nanopb/vendor/nanopb/generator/proto
    - make -C tmp/hardware-wallet emulator
    # On GNU/Linux wrap emulator in xvfb graphics context
    - xvfb-run --server-args="${XARGS}" make -C ./tmp/hardware-wallet run-emulator & true;
    # Run self-tests
    - ps aux | grep emulator
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy -docker build desktop
  
  - stage: "Windows"
    os: windows
    install:
    - go get -u -v github.com/therecipe/qt/cmd/...
    - ($(go env GOPATH)\bin\qtsetup -test=false | true)
    
    script:
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy build desktop 

  - stage: "MacOS"
    os: osx
    osx_image: xcode10.2
    script:
    - if [[ ! -d $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet ]]; then mkdir -p $GOPATH/src/github.com/fibercrypto; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet; fi
    - cd $GOPATH/src/github.com/fibercrypto/FiberCryptoWallet
    - xcode-select --install | true
    - go get -u -v github.com/therecipe/qt/cmd/... && ($(go env GOPATH)/bin/qtsetup -test=false | true)
    - go get -t -d -v ./...
    - $GOPATH/bin/qtdeploy build desktop
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
